version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: edu_mysql
    environment:
      MYSQL_ROOT_PASSWORD: fgdTv@4629uGdY
      MYSQL_DATABASE: dev_yundisoft
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      - edu_network

  redis:
    image: redis:7-alpine
    container_name: edu_redis
    command: redis-server --port 6380 --requirepass HaWSD*9265tZYj
    ports:
      - "6380:6380"
    volumes:
      - redis_data:/data
    networks:
      - edu_network

  backend:
    build: ./backend
    container_name: edu_backend
    volumes:
      - ./backend:/app
      - ./backend/config:/app/config
    environment:
      - GPT_ENV=DEV
      - IS_DOCKER=true
      - PYTHONPATH=/app
    depends_on:
      - mysql
      - redis
    networks:
      - edu_network

  frontend:
    build: 
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://9.135.78.24/api
        VITE_ENABLE_MOCK: false
    container_name: edu_frontend
    environment:
      - VITE_API_BASE_URL=http://9.135.78.24/api
      - VITE_ENABLE_MOCK=false
    volumes:
      - frontend_dist:/app/dist
    networks:
      - edu_network

  nginx:
    image: nginx:alpine
    container_name: edu_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/logs:/var/log/nginx
      - frontend_dist:/app/dist:ro
    depends_on:
      - backend
      - frontend
    networks:
      - edu_network

volumes:
  mysql_data:
  redis_data:
  frontend_dist:

networks:
  edu_network:
    driver: bridge 